# Generated by Django 5.0.1 on 2024-02-03 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='espece',
            name='nom_scientifique',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Nom scientifique'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('date_observation', models.DateField(verbose_name="Date d'observation")),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('notes', models.TextField(blank=True, default='pas de notes', verbose_name='Notes')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='faunatrack/static/photos_observations/', verbose_name='Photos')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='faunatrack.espece', verbose_name='Espèce')),
            ],
        ),
        migrations.CreateModel(
            name='Scientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, default='CNRS', max_length=250, verbose_name='Institution')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_scientifique', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('document', models.FileField(blank=True, null=True, upload_to='faunatrack/static/documents_projets/', verbose_name='Documents')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('observations', models.ManyToManyField(related_name='projets', to='faunatrack.observation', verbose_name='Observations')),
                ('responable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet', to='faunatrack.scientifique', verbose_name='Responsable')),
            ],
        ),
    ]
