# Generated by Django 5.0.1 on 2024-02-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0003_espece_statut_alter_observation_espece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos_observations/', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents_projets/', verbose_name='Documents'),
        ),
    ]
