# Generated by Django 5.0.1 on 2024-02-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0003_rename_responable_projet_responsable_and_more'),
        ('faunatrack', '0004_projet_slug_alter_observation_photos_and_more'),
    ]

    operations = [
    ]
