# Generated by Django 5.0.1 on 2024-02-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0005_merge_20240206_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espece',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='slug',
        ),
        migrations.AddField(
            model_name='espece',
            name='status',
            field=models.CharField(choices=[('DANGER', 'En danger'), ('SAIN', 'Hors de danger')], default='DANGER', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='faunatrack/static/photos_observations/', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='faunatrack/static/documents_projets/', verbose_name='Documents'),
        ),
    ]
