# Generated by Django 5.0.1 on 2024-02-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0006_remove_espece_statut_remove_projet_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
